#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "stm32f4xx.h"

/*
 * SkyStar STM32F407VET6 载板引脚总表。
 *
 * 这里是硬件连线的唯一代码来源：驱动文件只引用这些宏，不在各处重复写端口。
 * 车体方向约定为 P1 在左、P2 在右、USB 朝车尾；改线时优先同步本文件和 docs。
 */

/*
 * Dual TB6612FNG motor drive:
 *   - Left TB6612: left-front motor on channel A, left-rear motor on channel B.
 *   - Right TB6612: right-front motor on channel A, right-rear motor on channel B.
 * Four independent PWM outputs are generated by TIM5 on PA0..PA3.
 */
#define BOARD_MOTOR_PWM_PORT         GPIOA
#define BOARD_MOTOR_LF_PWM_PIN       0U
#define BOARD_MOTOR_LR_PWM_PIN       1U
#define BOARD_MOTOR_RF_PWM_PIN       2U
#define BOARD_MOTOR_RR_PWM_PIN       3U
#define BOARD_MOTOR_PWM_AF           2U

#define BOARD_MOTOR_CTRL_PORT        GPIOE
#define BOARD_MOTOR_LF_IN1_PIN       0U
#define BOARD_MOTOR_LF_IN2_PIN       1U
#define BOARD_MOTOR_LR_IN1_PIN       2U
#define BOARD_MOTOR_LR_IN2_PIN       3U
#define BOARD_MOTOR_LEFT_STBY_PIN    4U  /* Fit an external 10 kOhm pull-down. */
#define BOARD_MOTOR_RF_IN1_PIN       5U
#define BOARD_MOTOR_RF_IN2_PIN       6U
#define BOARD_MOTOR_RR_IN1_PIN       7U
#define BOARD_MOTOR_RR_IN2_PIN       8U
#define BOARD_MOTOR_RIGHT_STBY_PIN   10U /* PE9/PE11 are used by LF encoder. */

/* 编码器 AB 相引脚；前进计数正负不在这里改，统一在 Encoder.h 的 SIGN 中校准。 */
#define BOARD_ENCODER_LF_PORT        GPIOE
#define BOARD_ENCODER_LF_A_PIN       9U
#define BOARD_ENCODER_LF_B_PIN       11U
#define BOARD_ENCODER_LF_AF          1U
#define BOARD_ENCODER_LF_TIM         TIM1

#define BOARD_ENCODER_LR_PORT        GPIOD
#define BOARD_ENCODER_LR_A_PIN       12U
#define BOARD_ENCODER_LR_B_PIN       13U
#define BOARD_ENCODER_LR_AF          2U
#define BOARD_ENCODER_LR_TIM         TIM4

#define BOARD_ENCODER_RF_PORT        GPIOB
#define BOARD_ENCODER_RF_A_PIN       4U
#define BOARD_ENCODER_RF_B_PIN       5U
#define BOARD_ENCODER_RF_AF          2U
#define BOARD_ENCODER_RF_TIM         TIM3

#define BOARD_ENCODER_RR_PORT        GPIOC
#define BOARD_ENCODER_RR_A_PIN       6U
#define BOARD_ENCODER_RR_B_PIN       7U
#define BOARD_ENCODER_RR_AF          3U
#define BOARD_ENCODER_RR_TIM         TIM8

/* 安全输入和电池采样；PE12 是软件急停，不能替代物理断电急停。 */
#define BOARD_ESTOP_PORT             GPIOE
#define BOARD_ESTOP_PIN              12U
#define BOARD_ESTOP_ACTIVE_LEVEL     0U

#define BOARD_BATTERY_ADC            ADC1
#define BOARD_BATTERY_ADC_PORT       GPIOC
#define BOARD_BATTERY_ADC_PIN        0U
#define BOARD_BATTERY_ADC_CHANNEL    10U

/* PE13..PE15 remain free for payload release or future expansion IO. */

/* ICM-42688-P 接 SPI2，INT1 接 EXTI9 用于数据就绪提示。 */
#define BOARD_IMU_SPI                SPI2
#define BOARD_IMU_SPI_PORT           GPIOB
#define BOARD_IMU_SCK_PIN            13U
#define BOARD_IMU_MISO_PIN           14U
#define BOARD_IMU_MOSI_PIN           15U
#define BOARD_IMU_SPI_AF             5U
#define BOARD_IMU_CS_PORT            GPIOD
#define BOARD_IMU_CS_PIN             8U
#define BOARD_IMU_INT_PORT           GPIOD
#define BOARD_IMU_INT_PIN            9U

/* 树莓派/蓝牙透传共用 USART2 文本协议链路。 */
#define BOARD_BT_USART               USART2
#define BOARD_BT_PORT                GPIOD
#define BOARD_BT_TX_PIN              5U
#define BOARD_BT_RX_PIN              6U
#define BOARD_BT_AF                  7U

/* USART1 debug header is reserved and is not initialized by this firmware. */
#define BOARD_DEBUG_USART            USART1
#define BOARD_DEBUG_PORT             GPIOA
#define BOARD_DEBUG_TX_PIN           9U
#define BOARD_DEBUG_RX_PIN           10U
#define BOARD_DEBUG_AF               7U

/* Reserved board functions: USB PA11/PA12, TF PC8-PC12/PD2/PD3, Flash PA4-PA7. */

#define BOARD_PIN_MASK(pin)          ((uint16_t)(1UL << (pin)))

#endif
