#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include "stm32f4xx.h"

/*
 * SkyStar STM32F407VET6 carrier board pin map.
 * Vehicle orientation: P1 on the left, P2 on the right, USB toward the rear.
 */

/*
 * Dual TB6612FNG motor drive:
 *   - Left TB6612: left-front motor on channel A, left-rear motor on channel B.
 *   - Right TB6612: right-front motor on channel A, right-rear motor on channel B.
 * Four independent PWM outputs are generated by TIM5 on PA0..PA3.
 */
#define BOARD_MOTOR_PWM_PORT         GPIOA
#define BOARD_MOTOR_LF_PWM_PIN       0U
#define BOARD_MOTOR_LR_PWM_PIN       1U
#define BOARD_MOTOR_RF_PWM_PIN       2U
#define BOARD_MOTOR_RR_PWM_PIN       3U
#define BOARD_MOTOR_PWM_AF           2U

#define BOARD_MOTOR_CTRL_PORT        GPIOE
#define BOARD_MOTOR_LF_IN1_PIN       0U
#define BOARD_MOTOR_LF_IN2_PIN       1U
#define BOARD_MOTOR_LR_IN1_PIN       2U
#define BOARD_MOTOR_LR_IN2_PIN       3U
#define BOARD_MOTOR_LEFT_STBY_PIN    4U  /* Fit an external 10 kOhm pull-down. */
#define BOARD_MOTOR_RF_IN1_PIN       5U
#define BOARD_MOTOR_RF_IN2_PIN       6U
#define BOARD_MOTOR_RR_IN1_PIN       7U
#define BOARD_MOTOR_RR_IN2_PIN       8U
#define BOARD_MOTOR_RIGHT_STBY_PIN   10U /* PE9/PE11 are used by LF encoder. */

/* Encoder AB pairs. Forward count polarity is adjusted in Encoder.h. */
#define BOARD_ENCODER_LF_PORT        GPIOE
#define BOARD_ENCODER_LF_A_PIN       9U
#define BOARD_ENCODER_LF_B_PIN       11U
#define BOARD_ENCODER_LF_AF          1U
#define BOARD_ENCODER_LF_TIM         TIM1

#define BOARD_ENCODER_LR_PORT        GPIOD
#define BOARD_ENCODER_LR_A_PIN       12U
#define BOARD_ENCODER_LR_B_PIN       13U
#define BOARD_ENCODER_LR_AF          2U
#define BOARD_ENCODER_LR_TIM         TIM4

#define BOARD_ENCODER_RF_PORT        GPIOB
#define BOARD_ENCODER_RF_A_PIN       4U
#define BOARD_ENCODER_RF_B_PIN       5U
#define BOARD_ENCODER_RF_AF          2U
#define BOARD_ENCODER_RF_TIM         TIM3

#define BOARD_ENCODER_RR_PORT        GPIOC
#define BOARD_ENCODER_RR_A_PIN       6U
#define BOARD_ENCODER_RR_B_PIN       7U
#define BOARD_ENCODER_RR_AF          3U
#define BOARD_ENCODER_RR_TIM         TIM8

/* Safety inputs and power monitoring. */
#define BOARD_ESTOP_PORT             GPIOE
#define BOARD_ESTOP_PIN              12U
#define BOARD_ESTOP_ACTIVE_LEVEL     0U

#define BOARD_BATTERY_ADC            ADC1
#define BOARD_BATTERY_ADC_PORT       GPIOC
#define BOARD_BATTERY_ADC_PIN        0U
#define BOARD_BATTERY_ADC_CHANNEL    10U

/* PE13..PE15 remain free for payload release or future expansion IO. */

/* ICM-42688-P on SPI2. */
#define BOARD_IMU_SPI                SPI2
#define BOARD_IMU_SPI_PORT           GPIOB
#define BOARD_IMU_SCK_PIN            13U
#define BOARD_IMU_MISO_PIN           14U
#define BOARD_IMU_MOSI_PIN           15U
#define BOARD_IMU_SPI_AF             5U
#define BOARD_IMU_CS_PORT            GPIOD
#define BOARD_IMU_CS_PIN             8U
#define BOARD_IMU_INT_PORT           GPIOD
#define BOARD_IMU_INT_PIN            9U

/* Raspberry Pi motion and telemetry link on USART2. */
#define BOARD_BT_USART               USART2
#define BOARD_BT_PORT                GPIOD
#define BOARD_BT_TX_PIN              5U
#define BOARD_BT_RX_PIN              6U
#define BOARD_BT_AF                  7U

/* USART1 debug header is reserved and is not initialized by this firmware. */
#define BOARD_DEBUG_USART            USART1
#define BOARD_DEBUG_PORT             GPIOA
#define BOARD_DEBUG_TX_PIN           9U
#define BOARD_DEBUG_RX_PIN           10U
#define BOARD_DEBUG_AF               7U

/* Reserved board functions: USB PA11/PA12, TF PC8-PC12/PD2/PD3, Flash PA4-PA7. */

#define BOARD_PIN_MASK(pin)          ((uint16_t)(1UL << (pin)))

#endif
